/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package name.score;

import name.score.services.CharacterValueScoringService;
import name.score.services.FileUploadService;
import name.score.services.ScoringService;
import name.score.services.UploadService;

import java.io.IOException;
import java.io.Reader;
import java.util.List;

public class NameScore {

    private final ScoringService scoringService;

    private final UploadService uploadService;

    public NameScore(final ScoringService scoringService, final UploadService uploadService) {
        this.scoringService = scoringService;
        this.uploadService = uploadService;
    }

    public static void main(String[] args) {
        NameScore nameScore = new NameScore(new CharacterValueScoringService(), new FileUploadService());

        System.out.println("Score: " + nameScore.getScore(args));
    }

    int getScore(final String[] args) {
        int score = 0;
        try {
            Reader fileReader = uploadService.uploadRecords(args.length > 0 ? args[0] : "");
            List<String> names = uploadService.parseNameFile(fileReader);
            score = scoringService.calculateScore(names);
        } catch (IOException e) {
            System.out.println("An error occurred while calculating the name score. Exiting...");
        }
        return score;
    }
}
